//Celine Yan Period 5
#include <stdio.h>
#include <stdlib.h>

/*  Problem 2
Each new term in the Fibonacci sequence is generated by adding 
the previous two terms. By starting with 1 and 2, the first 10 terms 
will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not 
exceed four million, find the sum of the even-valued terms.
*/

int problem2() {
  int ans, prev;
  ans = prev = 0;
  int temp;
  int x = 1;
    prev = 0; 
    ans = 0;
    while (x < 4000000) {
        temp = prev;
        prev = x;
        x += temp;
        if (x % 2 == 0) {
            ans += x;
        }
    }
    return ans;
}

int main(){
	printf("%d \n", problem2());
	return 0;
}